services:

  web_server:
    depends_on:
      - db
    restart: always
    build:
      context: .
      dockerfile: src/Dockerfile
    image: web_server
    networks:
      - db
    environment:
      - PORT=${PORT}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - SECRET=${SECRET}

  db:
    restart: always
    image: mysql
    volumes:
      - db-data:/var/lib/mysql
      - ./epytodo.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    networks:
      - db

volumes:
  db-data:
    name: db-data
    driver: local

networks:
  db:
    driver: bridge
